name: CI Back-end (Branches)

on:
  push:
    branches:
<<<<<<< HEAD
        - '**'
        - '!main'
    paths:
        - 'sgcmapi/**'
=======
      - '**'
      - '!main'
    paths:
      - 'sgcmapi/**'

>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
jobs:
  main:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-backend.yml
  merge:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge Branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
<<<<<<< HEAD
          github_token: ${{ github.token }}
=======
          github_token: ${{ github.token }}
>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
