<<<<<<< HEAD
name: CI Back-end
=======
name: CI Back-end (Main)

>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'sgcmapi/**'
<<<<<<< HEAD
=======

>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
<<<<<<< HEAD
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: 'sgcmapi/'
=======
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
        run: mvn compile test
  merge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filtro de arquivos
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            java:
              - '**/*.java'
      - name: Merge branch
        if: steps.filter.outputs.java == 'false'
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
<<<<<<< HEAD
          github_token: ${{ github.token }}
=======
          github_token: ${{ github.token }}
>>>>>>> c7e9363569612b6b6d3c4c8fbbc020136571043b
